repos:
  - repo: .
    rev: 1.5.4
    hooks:
      - id: duolingo
        exclude: test/before
  - repo: local
    hooks:
      - id: test
        name: Tests
        entry: make test
        language: system
        always_run: true
